// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: protobuf/v1/PrivateStorage/private_storage.proto

package PrivateStorage

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projectname string       `protobuf:"bytes,1,opt,name=projectname,proto3" json:"projectname,omitempty"`
	Objectname  string       `protobuf:"bytes,2,opt,name=objectname,proto3" json:"objectname,omitempty"`
	Option      *File_Option `protobuf:"bytes,3,opt,name=option,proto3" json:"option,omitempty"`
	File        []byte       `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetProjectname() string {
	if x != nil {
		return x.Projectname
	}
	return ""
}

func (x *File) GetObjectname() string {
	if x != nil {
		return x.Objectname
	}
	return ""
}

func (x *File) GetOption() *File_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *File) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type FileLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *FileLocation) Reset() {
	*x = FileLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLocation) ProtoMessage() {}

func (x *FileLocation) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLocation.ProtoReflect.Descriptor instead.
func (*FileLocation) Descriptor() ([]byte, []int) {
	return file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescGZIP(), []int{1}
}

func (x *FileLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type File_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
}

func (x *File_Option) Reset() {
	*x = File_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File_Option) ProtoMessage() {}

func (x *File_Option) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File_Option.ProtoReflect.Descriptor instead.
func (*File_Option) Descriptor() ([]byte, []int) {
	return file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *File_Option) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_protobuf_v1_PrivateStorage_private_storage_proto protoreflect.FileDescriptor

var file_protobuf_v1_PrivateStorage_private_storage_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbd, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x1a, 0x2a, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x2a, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xce, 0x01, 0x0a, 0x0e,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3c,
	0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x1c,
	0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x08,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x14, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x49, 0x5a, 0x47,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x65, 0x62, 0x65,
	0x72, 0x2d, 0x69, 0x64, 0x2f, 0x77, 0x65, 0x65, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescOnce sync.Once
	file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescData = file_protobuf_v1_PrivateStorage_private_storage_proto_rawDesc
)

func file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescGZIP() []byte {
	file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescOnce.Do(func() {
		file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescData)
	})
	return file_protobuf_v1_PrivateStorage_private_storage_proto_rawDescData
}

var file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_v1_PrivateStorage_private_storage_proto_goTypes = []interface{}{
	(*File)(nil),         // 0: PrivateStorage.File
	(*FileLocation)(nil), // 1: PrivateStorage.FileLocation
	(*File_Option)(nil),  // 2: PrivateStorage.File.Option
	(*empty.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_protobuf_v1_PrivateStorage_private_storage_proto_depIdxs = []int32{
	2, // 0: PrivateStorage.File.option:type_name -> PrivateStorage.File.Option
	0, // 1: PrivateStorage.PrivateStorage.Upload:input_type -> PrivateStorage.File
	1, // 2: PrivateStorage.PrivateStorage.Download:input_type -> PrivateStorage.FileLocation
	1, // 3: PrivateStorage.PrivateStorage.Delete:input_type -> PrivateStorage.FileLocation
	1, // 4: PrivateStorage.PrivateStorage.Upload:output_type -> PrivateStorage.FileLocation
	0, // 5: PrivateStorage.PrivateStorage.Download:output_type -> PrivateStorage.File
	3, // 6: PrivateStorage.PrivateStorage.Delete:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_v1_PrivateStorage_private_storage_proto_init() }
func file_protobuf_v1_PrivateStorage_private_storage_proto_init() {
	if File_protobuf_v1_PrivateStorage_private_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_v1_PrivateStorage_private_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_v1_PrivateStorage_private_storage_proto_goTypes,
		DependencyIndexes: file_protobuf_v1_PrivateStorage_private_storage_proto_depIdxs,
		MessageInfos:      file_protobuf_v1_PrivateStorage_private_storage_proto_msgTypes,
	}.Build()
	File_protobuf_v1_PrivateStorage_private_storage_proto = out.File
	file_protobuf_v1_PrivateStorage_private_storage_proto_rawDesc = nil
	file_protobuf_v1_PrivateStorage_private_storage_proto_goTypes = nil
	file_protobuf_v1_PrivateStorage_private_storage_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrivateStorageClient is the client API for PrivateStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivateStorageClient interface {
	Upload(ctx context.Context, in *File, opts ...grpc.CallOption) (*FileLocation, error)
	Download(ctx context.Context, in *FileLocation, opts ...grpc.CallOption) (*File, error)
	Delete(ctx context.Context, in *FileLocation, opts ...grpc.CallOption) (*empty.Empty, error)
}

type privateStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateStorageClient(cc grpc.ClientConnInterface) PrivateStorageClient {
	return &privateStorageClient{cc}
}

func (c *privateStorageClient) Upload(ctx context.Context, in *File, opts ...grpc.CallOption) (*FileLocation, error) {
	out := new(FileLocation)
	err := c.cc.Invoke(ctx, "/PrivateStorage.PrivateStorage/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateStorageClient) Download(ctx context.Context, in *FileLocation, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/PrivateStorage.PrivateStorage/Download", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateStorageClient) Delete(ctx context.Context, in *FileLocation, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/PrivateStorage.PrivateStorage/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivateStorageServer is the server API for PrivateStorage service.
type PrivateStorageServer interface {
	Upload(context.Context, *File) (*FileLocation, error)
	Download(context.Context, *FileLocation) (*File, error)
	Delete(context.Context, *FileLocation) (*empty.Empty, error)
}

// UnimplementedPrivateStorageServer can be embedded to have forward compatible implementations.
type UnimplementedPrivateStorageServer struct {
}

func (*UnimplementedPrivateStorageServer) Upload(context.Context, *File) (*FileLocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedPrivateStorageServer) Download(context.Context, *FileLocation) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedPrivateStorageServer) Delete(context.Context, *FileLocation) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPrivateStorageServer(s *grpc.Server, srv PrivateStorageServer) {
	s.RegisterService(&_PrivateStorage_serviceDesc, srv)
}

func _PrivateStorage_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateStorageServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PrivateStorage.PrivateStorage/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateStorageServer).Upload(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateStorage_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateStorageServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PrivateStorage.PrivateStorage/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateStorageServer).Download(ctx, req.(*FileLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateStorage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateStorageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PrivateStorage.PrivateStorage/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateStorageServer).Delete(ctx, req.(*FileLocation))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivateStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PrivateStorage.PrivateStorage",
	HandlerType: (*PrivateStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _PrivateStorage_Upload_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _PrivateStorage_Download_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PrivateStorage_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/v1/PrivateStorage/private_storage.proto",
}
